name: Godwoken Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  godwoken-tests:
    uses: nervosnetwork/godwoken-tests/.github/workflows/reusable-integration-test-v1.yml@90a0cee5c5f1a43d47e3ea72f9f9f248e5a5d979
    with:
      extra_github_env: |
        MANUAL_BUILD_WEB3=true
        MANUAL_BUILD_WEB3_INDEXER=true
        WEB3_GIT_URL=https://github.com/${{ github.repository }}
        WEB3_GIT_CHECKOUT=${{ github.ref }}
